name 'little-app'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures little-app'
long_description 'Installs/Configures little-app'
version '0.1.0'
